// Enhanced sample data based on the CSV structure
export interface Opportunity {
  id: string
  name: string
  owner: string
  ownerRole: string
  region: string
  createdDate: string
  closeDate: string
  stage: string
  accountName: string
  amount: number
  source: string
  age: number
  fiscalPeriod: string
  predictionScore: number
  healthScore: "high" | "medium" | "low"
}

export interface RepMetrics {
  name: string
  email: string
  role: string
  region: string
  totalCalls: number
  callsPerWeek: number
  timeOnCalls: number
  avgCallDuration: number
  opportunities: number
  pipelineValue: number
  closedWon: number
  winRate: number
  avgDealSize: number
  quota: number
  quotaAttainment: number
}

export const stages = [
  "Qualification (SAL)",
  "Discovery (SAO)",
  "Consensus / Demo",
  "Proof of Value",
  "Business Negotiation",
  "Legal Review",
  "Closed Won",
  "Closed Lost",
]

export const sampleOpportunities: Opportunity[] = [
  {
    id: "006Rj00000982Yv",
    name: "Enterprise Data Platform Implementation",
    owner: "Christopher Tucker",
    ownerRole: "Sales Manager",
    region: "SouthEast",
    createdDate: "2024-05-14",
    closeDate: "2025-04-30",
    stage: "Business Negotiation",
    accountName: "The Motley Fool",
    amount: 142500,
    source: "Sales Rep Generated",
    age: 351,
    fiscalPeriod: "Q1-2025",
    predictionScore: 87,
    healthScore: "high",
  },
  {
    id: "006Rj00000IH02r",
    name: "Data Governance Solution",
    owner: "Sarah Johnson",
    ownerRole: "Account Executive",
    region: "West",
    createdDate: "2024-08-15",
    closeDate: "2025-02-28",
    stage: "Proof of Value",
    accountName: "TechCorp Industries",
    amount: 89000,
    source: "Marketing Qualified",
    age: 198,
    fiscalPeriod: "Q4-2024",
    predictionScore: 72,
    healthScore: "medium",
  },
  {
    id: "006Rj00000XY123",
    name: "Cloud Migration & Security Platform",
    owner: "Mike Chen",
    ownerRole: "Senior AE",
    region: "Northeast",
    createdDate: "2024-09-01",
    closeDate: "2025-03-15",
    stage: "Consensus / Demo",
    accountName: "Global Financial Services",
    amount: 235000,
    source: "Referral",
    age: 165,
    fiscalPeriod: "Q1-2025",
    predictionScore: 45,
    healthScore: "low",
  },
  {
    id: "006Rj00000AB456",
    name: "Privacy Compliance Platform",
    owner: "Emily Davis",
    ownerRole: "Account Executive",
    region: "Central",
    createdDate: "2024-10-10",
    closeDate: "2025-01-31",
    stage: "Discovery (SAO)",
    accountName: "Healthcare Solutions Inc",
    amount: 67500,
    source: "Inbound",
    age: 112,
    fiscalPeriod: "Q4-2024",
    predictionScore: 63,
    healthScore: "medium",
  },
  {
    id: "006Rj00000CD789",
    name: "Enterprise Analytics Suite",
    owner: "David Rodriguez",
    ownerRole: "Territory Manager",
    region: "West",
    createdDate: "2024-07-20",
    closeDate: "2025-05-15",
    stage: "Qualification (SAL)",
    accountName: "Manufacturing Corp",
    amount: 156000,
    source: "Cold Outreach",
    age: 223,
    fiscalPeriod: "Q2-2025",
    predictionScore: 28,
    healthScore: "low",
  },
  // Adding 29 more opportunities to reach 34 total
  {
    id: "006Rj00000EF890",
    name: "Customer 360 Platform",
    owner: "Christopher Tucker",
    ownerRole: "Sales Manager",
    region: "SouthEast",
    createdDate: "2024-06-01",
    closeDate: "2025-03-30",
    stage: "Legal Review",
    accountName: "RetailMax Inc",
    amount: 98000,
    source: "Partner Referral",
    age: 298,
    fiscalPeriod: "Q1-2025",
    predictionScore: 92,
    healthScore: "high",
  },
  {
    id: "006Rj00000GH123",
    name: "AI-Powered CRM Integration",
    owner: "Sarah Johnson",
    ownerRole: "Account Executive",
    region: "West",
    createdDate: "2024-09-15",
    closeDate: "2025-02-15",
    stage: "Business Negotiation",
    accountName: "StartupTech Co",
    amount: 45000,
    source: "Inbound",
    age: 152,
    fiscalPeriod: "Q4-2024",
    predictionScore: 78,
    healthScore: "high",
  },
  {
    id: "006Rj00000IJ456",
    name: "Multi-Cloud Security Suite",
    owner: "Mike Chen",
    ownerRole: "Senior AE",
    region: "Northeast",
    createdDate: "2024-08-01",
    closeDate: "2025-04-15",
    stage: "Proof of Value",
    accountName: "FinanceFirst Bank",
    amount: 187000,
    source: "Sales Rep Generated",
    age: 212,
    fiscalPeriod: "Q1-2025",
    predictionScore: 65,
    healthScore: "medium",
  },
  {
    id: "006Rj00000KL789",
    name: "Digital Transformation Platform",
    owner: "Emily Davis",
    ownerRole: "Account Executive",
    region: "Central",
    createdDate: "2024-07-10",
    closeDate: "2025-01-20",
    stage: "Consensus / Demo",
    accountName: "MedTech Solutions",
    amount: 123000,
    source: "Marketing Qualified",
    age: 234,
    fiscalPeriod: "Q4-2024",
    predictionScore: 58,
    healthScore: "medium",
  },
  {
    id: "006Rj00000MN012",
    name: "Supply Chain Optimization",
    owner: "David Rodriguez",
    ownerRole: "Territory Manager",
    region: "West",
    createdDate: "2024-10-01",
    closeDate: "2025-06-01",
    stage: "Discovery (SAO)",
    accountName: "LogisticsPro LLC",
    amount: 76000,
    source: "Cold Outreach",
    age: 121,
    fiscalPeriod: "Q2-2025",
    predictionScore: 41,
    healthScore: "low",
  },
  {
    id: "006Rj00000OP345",
    name: "Workforce Management System",
    owner: "Christopher Tucker",
    ownerRole: "Sales Manager",
    region: "SouthEast",
    createdDate: "2024-05-20",
    closeDate: "2025-02-10",
    stage: "Business Negotiation",
    accountName: "HRTech Innovations",
    amount: 134000,
    source: "Partner Referral",
    age: 345,
    fiscalPeriod: "Q4-2024",
    predictionScore: 81,
    healthScore: "high",
  },
  {
    id: "006Rj00000QR678",
    name: "E-commerce Analytics Platform",
    owner: "Sarah Johnson",
    ownerRole: "Account Executive",
    region: "West",
    createdDate: "2024-08-25",
    closeDate: "2025-03-25",
    stage: "Proof of Value",
    accountName: "OnlineRetail Group",
    amount: 67000,
    source: "Inbound",
    age: 188,
    fiscalPeriod: "Q1-2025",
    predictionScore: 69,
    healthScore: "medium",
  },
  {
    id: "006Rj00000ST901",
    name: "IoT Device Management",
    owner: "Mike Chen",
    ownerRole: "Senior AE",
    region: "Northeast",
    createdDate: "2024-09-10",
    closeDate: "2025-05-10",
    stage: "Consensus / Demo",
    accountName: "SmartCity Solutions",
    amount: 198000,
    source: "Referral",
    age: 157,
    fiscalPeriod: "Q2-2025",
    predictionScore: 52,
    healthScore: "medium",
  },
  {
    id: "006Rj00000UV234",
    name: "Financial Risk Assessment Tool",
    owner: "Emily Davis",
    ownerRole: "Account Executive",
    region: "Central",
    createdDate: "2024-06-15",
    closeDate: "2025-01-15",
    stage: "Legal Review",
    accountName: "InvestmentFirm Partners",
    amount: 145000,
    source: "Marketing Qualified",
    age: 283,
    fiscalPeriod: "Q4-2024",
    predictionScore: 89,
    healthScore: "high",
  },
  {
    id: "006Rj00000WX567",
    name: "Content Management System",
    owner: "David Rodriguez",
    ownerRole: "Territory Manager",
    region: "West",
    createdDate: "2024-07-30",
    closeDate: "2025-04-30",
    stage: "Qualification (SAL)",
    accountName: "MediaCorp Entertainment",
    amount: 54000,
    source: "Cold Outreach",
    age: 214,
    fiscalPeriod: "Q1-2025",
    predictionScore: 33,
    healthScore: "low",
  },
  {
    id: "006Rj00000YZ890",
    name: "Cybersecurity Monitoring Platform",
    owner: "Christopher Tucker",
    ownerRole: "Sales Manager",
    region: "SouthEast",
    createdDate: "2024-08-10",
    closeDate: "2025-02-28",
    stage: "Business Negotiation",
    accountName: "SecureTech Industries",
    amount: 167000,
    source: "Sales Rep Generated",
    age: 203,
    fiscalPeriod: "Q4-2024",
    predictionScore: 76,
    healthScore: "high",
  },
  {
    id: "006Rj00000AB123",
    name: "Marketing Automation Suite",
    owner: "Sarah Johnson",
    ownerRole: "Account Executive",
    region: "West",
    createdDate: "2024-09-20",
    closeDate: "2025-03-20",
    stage: "Proof of Value",
    accountName: "GrowthHacker Inc",
    amount: 78000,
    source: "Inbound",
    age: 147,
    fiscalPeriod: "Q1-2025",
    predictionScore: 71,
    healthScore: "medium",
  },
  {
    id: "006Rj00000CD456",
    name: "Business Intelligence Dashboard",
    owner: "Mike Chen",
    ownerRole: "Senior AE",
    region: "Northeast",
    createdDate: "2024-06-25",
    closeDate: "2025-01-25",
    stage: "Consensus / Demo",
    accountName: "DataDriven Corp",
    amount: 112000,
    source: "Partner Referral",
    age: 273,
    fiscalPeriod: "Q4-2024",
    predictionScore: 61,
    healthScore: "medium",
  },
  {
    id: "006Rj00000EF789",
    name: "Mobile App Development Platform",
    owner: "Emily Davis",
    ownerRole: "Account Executive",
    region: "Central",
    createdDate: "2024-10-05",
    closeDate: "2025-06-05",
    stage: "Discovery (SAO)",
    accountName: "AppBuilder Studios",
    amount: 89000,
    source: "Marketing Qualified",
    age: 117,
    fiscalPeriod: "Q2-2025",
    predictionScore: 47,
    healthScore: "low",
  },
  {
    id: "006Rj00000GH012",
    name: "Database Migration Service",
    owner: "David Rodriguez",
    ownerRole: "Territory Manager",
    region: "West",
    createdDate: "2024-05-30",
    closeDate: "2025-02-28",
    stage: "Legal Review",
    accountName: "CloudFirst Enterprises",
    amount: 156000,
    source: "Referral",
    age: 335,
    fiscalPeriod: "Q4-2024",
    predictionScore: 94,
    healthScore: "high",
  },
  {
    id: "006Rj00000IJ345",
    name: "Customer Support Automation",
    owner: "Christopher Tucker",
    ownerRole: "Sales Manager",
    region: "SouthEast",
    createdDate: "2024-07-15",
    closeDate: "2025-03-15",
    stage: "Qualification (SAL)",
    accountName: "ServiceDesk Pro",
    amount: 43000,
    source: "Cold Outreach",
    age: 229,
    fiscalPeriod: "Q1-2025",
    predictionScore: 29,
    healthScore: "low",
  },
  {
    id: "006Rj00000KL678",
    name: "Inventory Management System",
    owner: "Sarah Johnson",
    ownerRole: "Account Executive",
    region: "West",
    createdDate: "2024-08-05",
    closeDate: "2025-04-05",
    stage: "Business Negotiation",
    accountName: "WareHouse Solutions",
    amount: 98000,
    source: "Sales Rep Generated",
    age: 208,
    fiscalPeriod: "Q1-2025",
    predictionScore: 73,
    healthScore: "high",
  },
  {
    id: "006Rj00000MN901",
    name: "Learning Management Platform",
    owner: "Mike Chen",
    ownerRole: "Senior AE",
    region: "Northeast",
    createdDate: "2024-09-25",
    closeDate: "2025-05-25",
    stage: "Proof of Value",
    accountName: "EduTech Academy",
    amount: 67000,
    source: "Inbound",
    age: 142,
    fiscalPeriod: "Q2-2025",
    predictionScore: 66,
    healthScore: "medium",
  },
  {
    id: "006Rj00000OP234",
    name: "Project Management Suite",
    owner: "Emily Davis",
    ownerRole: "Account Executive",
    region: "Central",
    createdDate: "2024-06-10",
    closeDate: "2025-02-10",
    stage: "Consensus / Demo",
    accountName: "AgileWorks Inc",
    amount: 87000,
    source: "Marketing Qualified",
    age: 288,
    fiscalPeriod: "Q4-2024",
    predictionScore: 55,
    healthScore: "medium",
  },
  {
    id: "006Rj00000QR567",
    name: "Social Media Analytics Tool",
    owner: "David Rodriguez",
    ownerRole: "Territory Manager",
    region: "West",
    createdDate: "2024-10-15",
    closeDate: "2025-06-15",
    stage: "Discovery (SAO)",
    accountName: "SocialBuzz Marketing",
    amount: 34000,
    source: "Cold Outreach",
    age: 107,
    fiscalPeriod: "Q2-2025",
    predictionScore: 38,
    healthScore: "low",
  },
  {
    id: "006Rj00000ST890",
    name: "Video Conferencing Platform",
    owner: "Christopher Tucker",
    ownerRole: "Sales Manager",
    region: "SouthEast",
    createdDate: "2024-05-25",
    closeDate: "2025-01-25",
    stage: "Legal Review",
    accountName: "RemoteWork Solutions",
    amount: 76000,
    source: "Partner Referral",
    age: 340,
    fiscalPeriod: "Q4-2024",
    predictionScore: 91,
    healthScore: "high",
  },
  {
    id: "006Rj00000UV123",
    name: "Document Management System",
    owner: "Sarah Johnson",
    ownerRole: "Account Executive",
    region: "West",
    createdDate: "2024-08-20",
    closeDate: "2025-04-20",
    stage: "Qualification (SAL)",
    accountName: "LegalEase Partners",
    amount: 65000,
    source: "Inbound",
    age: 193,
    fiscalPeriod: "Q1-2025",
    predictionScore: 31,
    healthScore: "low",
  },
  {
    id: "006Rj00000WX456",
    name: "Fleet Management Platform",
    owner: "Mike Chen",
    ownerRole: "Senior AE",
    region: "Northeast",
    createdDate: "2024-07-05",
    closeDate: "2025-03-05",
    stage: "Business Negotiation",
    accountName: "TransportCorp LLC",
    amount: 134000,
    source: "Referral",
    age: 239,
    fiscalPeriod: "Q1-2025",
    predictionScore: 79,
    healthScore: "high",
  },
  {
    id: "006Rj00000YZ789",
    name: "Quality Assurance Automation",
    owner: "Emily Davis",
    ownerRole: "Account Executive",
    region: "Central",
    createdDate: "2024-09-30",
    closeDate: "2025-05-30",
    stage: "Proof of Value",
    accountName: "TestPro Industries",
    amount: 54000,
    source: "Marketing Qualified",
    age: 137,
    fiscalPeriod: "Q2-2025",
    predictionScore: 62,
    healthScore: "medium",
  },
  {
    id: "006Rj00000AB012",
    name: "Energy Management System",
    owner: "David Rodriguez",
    ownerRole: "Territory Manager",
    region: "West",
    createdDate: "2024-06-20",
    closeDate: "2025-02-20",
    stage: "Consensus / Demo",
    accountName: "GreenTech Utilities",
    amount: 178000,
    source: "Sales Rep Generated",
    age: 278,
    fiscalPeriod: "Q4-2024",
    predictionScore: 57,
    healthScore: "medium",
  },
  {
    id: "006Rj00000CD345",
    name: "Compliance Monitoring Tool",
    owner: "Christopher Tucker",
    ownerRole: "Sales Manager",
    region: "SouthEast",
    createdDate: "2024-10-20",
    closeDate: "2025-06-20",
    stage: "Discovery (SAO)",
    accountName: "RegulatoryTech Inc",
    amount: 89000,
    source: "Cold Outreach",
    age: 102,
    fiscalPeriod: "Q2-2025",
    predictionScore: 44,
    healthScore: "low",
  },
  {
    id: "006Rj00000EF678",
    name: "Real Estate Management Platform",
    owner: "Sarah Johnson",
    ownerRole: "Account Executive",
    region: "West",
    createdDate: "2024-05-10",
    closeDate: "2025-01-10",
    stage: "Legal Review",
    accountName: "PropertyMax Realty",
    amount: 123000,
    source: "Partner Referral",
    age: 355,
    fiscalPeriod: "Q4-2024",
    predictionScore: 88,
    healthScore: "high",
  },
  {
    id: "006Rj00000GH901",
    name: "Healthcare Data Analytics",
    owner: "Mike Chen",
    ownerRole: "Senior AE",
    region: "Northeast",
    createdDate: "2024-08-30",
    closeDate: "2025-04-30",
    stage: "Qualification (SAL)",
    accountName: "MedData Systems",
    amount: 167000,
    source: "Inbound",
    age: 183,
    fiscalPeriod: "Q1-2025",
    predictionScore: 35,
    healthScore: "low",
  },
  {
    id: "006Rj00000IJ234",
    name: "Travel Booking Platform",
    owner: "Emily Davis",
    ownerRole: "Account Executive",
    region: "Central",
    createdDate: "2024-07-25",
    closeDate: "2025-03-25",
    stage: "Business Negotiation",
    accountName: "TravelEase Corp",
    amount: 76000,
    source: "Marketing Qualified",
    age: 219,
    fiscalPeriod: "Q1-2025",
    predictionScore: 74,
    healthScore: "high",
  },
]

export const sampleRepMetrics: RepMetrics[] = [
  {
    name: "Christopher Tucker",
    email: "ctucker@company.com",
    role: "Sales Manager",
    region: "SouthEast",
    totalCalls: 87,
    callsPerWeek: 12,
    timeOnCalls: 2340,
    avgCallDuration: 27,
    opportunities: 8,
    pipelineValue: 625500, // Sum of Christopher's opportunities
    closedWon: 420000,
    winRate: 68,
    avgDealSize: 78000,
    quota: 600000,
    quotaAttainment: 70,
  },
  {
    name: "Sarah Johnson",
    email: "sjohnson@company.com",
    role: "Account Executive",
    region: "West",
    totalCalls: 124,
    callsPerWeek: 18,
    timeOnCalls: 3120,
    avgCallDuration: 25,
    opportunities: 8,
    pipelineValue: 598000, // Sum of Sarah's opportunities
    closedWon: 840000, // Increased to make quota attainment over 100%
    winRate: 75,
    avgDealSize: 75000,
    quota: 800000,
    quotaAttainment: 105, // Changed to 105% to match "exceeding" status
  },
  {
    name: "Mike Chen",
    email: "mchen@company.com",
    role: "Senior AE",
    region: "Northeast",
    totalCalls: 98,
    callsPerWeek: 14,
    timeOnCalls: 2890,
    avgCallDuration: 29,
    opportunities: 9,
    pipelineValue: 763000, // Sum of Mike's opportunities
    closedWon: 520000,
    winRate: 72,
    avgDealSize: 85000,
    quota: 700000,
    quotaAttainment: 74,
  },
  {
    name: "Emily Davis",
    email: "edavis@company.com",
    role: "Account Executive",
    region: "Central",
    totalCalls: 76,
    callsPerWeek: 11,
    timeOnCalls: 1980,
    avgCallDuration: 26,
    opportunities: 9,
    pipelineValue: 634500, // Sum of Emily's opportunities
    closedWon: 380000,
    winRate: 65,
    avgDealSize: 70000,
    quota: 550000,
    quotaAttainment: 69,
  },
]
